name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
      - uses: actions/setup-java@v4
        with:
          java-version: "16"
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bundleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: app/build/outputs
